### ISSUE TITLE
Can you share source about Unity Avatar Retargeting?

### ISSUE THREAD

**Issue by skcskc7** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#17]
hello

In this video (https://www.youtube.com/watch?time_continue=208&v=rZn15BRf77E), there is a Unity Regargeting section. 

Can you share the source?

Thank you

**Comment by xiangdonglai** [comment]
The avatar was purchased from the Unity store, so it is proprietary. We are not allowed to release it due to copyright reasons. However, we do the retargeting in a very straightforward manner. A rig is set up to be the same as the Adam model for the avatar. Then we directly feed the joint angles of Adam model to the avatar.

**Comment by hellozjj** [comment]
@xiangdonglai , how about the root position?  Did you directly set the root position as the bvh file root position? I used other 3d pose estimation methods, and they don't give the root position in the world coordinate. Is the root postion in your output bvh file in  the world coordinate?
