### ISSUE TITLE
Run without visualization?

### ISSUE THREAD

**Issue by ZhengyiLuo** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#20]
Would it be possible to run with visualization and directly write the result to disk? I am running this in a docker image and getting the OpenGL to work proves to be troublesome. 

Thanks a ton!

**Comment by xiangdonglai** [comment]
There are 2 possibilities as far as I know.

1. In 'run_fitting.cpp', you can comment out all lines that contain 'Renderer' or 'render', or the lines that read outputs from the renderer. In this way you will still get output in terms of Adam parameters in 'txt' files, but not the visualized images.

2. The other way is to substitute the OpenGL renderer with EGL, but you will need to do some engineering yourself there.

I think solution 1 is in general easier. because once you save the Adam model parameters and reconstruct the result to a mesh as I did [here](https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture/blob/master/FitAdam/run_fitting.cpp#L589), you can visualize the results using any other graphical tools that can render a mesh. Hope this will help you.

**Comment by wtnan2003** [comment]
@ZhengyiLuo would it be possible for you to share a dockerfile or docker image with me? thx!

**Comment by nopeiyu** [comment]
> There are 2 possibilities as far as I know.
> 
> 1. In 'run_fitting.cpp', you can comment out all lines that contain 'Renderer' or 'render', or the lines that read outputs from the renderer. In this way you will still get output in terms of Adam parameters in 'txt' files, but not the visualized images.
> 2. The other way is to substitute the OpenGL renderer with EGL, but you will need to do some engineering yourself there.
> 
> I think solution 1 is in general easier. because once you save the Adam model parameters and reconstruct the result to a mesh as I did [here](https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture/blob/master/FitAdam/run_fitting.cpp#L589), you can visualize the results using any other graphical tools that can render a mesh. Hope this will help you.

I modified the code according to your method 1. It can run successfully on the remote server, but the output result is very poor. It seems that render is necessary for optical flow. How can I modify it to run correctly on the remote server? I look forward to your reply
