### ISSUE TITLE
OpenCV4 version  issue : purpose of meshTrackingProj.cpp?

### ISSUE THREAD

**Issue by HelloEgg** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#34]
Hi.

First of all, thank  you very much for your great work! 

While I was making FitAdam, (make -j12 as instructed), 

It looks like meshTrackingProj.cpp seems to cause problem.

In import statement,

#include "opencv2/gpu/gpu.hpp"

looks deprecated for opencv versions over 3.4 (I'm using 3.4. Couldn't install 2.4.13 since it is not compatible with my CUDA version)

What is meshTrackingProj.cpp used for? is it crucial for rendering Adam model?

Thank you.

**Comment by HelloEgg** [comment]
Ok. So I replaced 

#include "opencv2/gpu/gpu.hpp"

to 
#include "opencv2/core/cuda.hpp"

and changed all name spaces gpu to cuda like this:
cv:gpu -> cv:cuda

As in this case, in order to import
BroxOpricalFlow 

I needed 
#include <opencv2/cudaoptflow.hpp>
which is not present... 
do you have any suggestion on this issue?

**Comment by HelloEgg** [comment]
Hi. 

**I managed to modify codes to satisfy Opencv 4.** Some file dependencies and functions are changed as of OpenCV4. 

1. in meshTrackingProj.cpp, 
change 
#include "opencv2/gpu/gpu.hpp"
to 
#include "opencv2/core/cuda.hpp"
#include "opencv2/cudaarithm.hpp"
#include "opencv2/cudaoptflow.hpp"
#include <opencv2/core/utility.hpp>
#include "opencv2/core.hpp"

Some dependencies may be unnecessay.

2. In meshTrackingProj.cpp

change gpu name spaces to cuda.

For instance,
cv::gpu::GpuMat
to 
cv::cuda::GpuMat

3. In meshTrackingProj.cpp

change 

        cv::gpu::BroxOpticalFlow brox_flow(brox_alpha, brox_gamma, brox_scale, brox_inner, brox_outer, brox_solver);

to following : 

        cv::Ptr<cv::cuda::BroxOpticalFlow> brox_flow = cv::cuda::BroxOpticalFlow::create(brox_alpha, brox_gamma, brox_scale, brox_inner, brox_outer, brox_solver);

Explanation : 
In OpenCV2, BroxOpticalFlow operator overloading was declared for "( )" (Parentheses) to create BroxOpticalFlow instance. 

However, in OpenCV4, this has been replaced to cv::cuda::BroxOpticalFlow::create.

So, one must create and declare BroxOpticalFlow instance as cv::Ptr variable.

4. Some function names have been changed. (In utils.cpp and other files)
Change

		cv::cvtColor(foreGround, foreGround, CV_BGR2GRAY);

to

 		cv::cvtColor(foreGround, foreGround, cv::COLOR_BGR2GRAY);

Note that you only need to change CV_BGR2GRAY to cv::COLOR_BGR2GRAY

5. I found it much easier to install OpenCV4 and configure than installing OpenCV2 and modify everything.
It looks like OpenCV2 does not support recent architectures including tesla, which I am using right now. Please correct me if I'm wrong.

After those configuratios, I was able to implement total capture to my pipeline!

**Comment by xiangdonglai** [comment]
Sorry for the late reply. This file was basically handling the texture-based tracking of the meshes, as mentioned in Section 6 of the paper.

I am sorry that I don't have time to test other versions of the dependencies. I am glad that you figure this out yourself.

**Comment by HelloEgg** [comment]
@xiangdonglai  Glad that I can contribute to community! I will close this issue for now! Hope someone can get help from my comments :)

**Comment by wubowen416** [comment]
@HelloEgg Many thanks for the guidance to use opencv4.

One problem I encountered was the brox_flow has no member function that is compatible to the input tuple `(frame0, frame1, cuda_fu, cuda_fv)` in the call `brox_flow(frame0, frame1, cuda_fu, cuda_fv);` in meshTrackingProj.cpp around line 66.

The error was:
`error: no match for call to '(cv::Ptr<cv::cuda::BroxOpticalFlow>) (cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&)' 
66 |         brox_flow(frame0, frame1, cuda_fu, cuda_fv);`

I looked up the opencv4 docs, there is only a member function that is similar to this call, but the type of arguments does not match this call:
`calc (InputArray I0, InputArray I1, InputOutputArray flow, Stream &stream=Stream::Null())=0 `
from https://docs.opencv.org/4.x/d7/d18/classcv_1_1cuda_1_1BroxOpticalFlow.html.
I tried to call brox_flow->calc() but it does not work since the argument type does not match.

I also looked up opencv2 docs, where there is a member function to match this call:
`void operator ()(const GpuMat& frame0, const GpuMat& frame1, GpuMat& u, GpuMat& v, Stream& stream = Stream::Null());`
from https://www.opencv.org.cn/opencvdoc/2.3.2/html/modules/gpu/doc/video.html?highlight=opticalflow#gpu-broxopticalflow. But I could not find it in cv4.

Did the function in cv2 disappear in cv4? Which function should I use? Did you have this problem either?

I'm using opencv4.6, and opencv_contrib, compiled from source. All of the arguments for compliation were same as the Dockerfile provided by this repo.

**Comment by wubowen416** [comment]
Managed to solve the problem by replacing:
```
cv::cuda::GpuMat cuda_fu, cuda_fv, cuda_bu, cuda_bv;
brox_flow(frame0, frame1, cuda_fu, cuda_fv);
brox_flow(frame1, frame0, cuda_bu, cuda_bv);
cv::Mat fu(cuda_fu), fv(cuda_fv), bu(cuda_bu), bv(cuda_bv);
```
to:
```
// compute flow horizontal and vertical simultaneously
cv::cuda::GpuMat cuda_flow_f(frame0.size(), CV_32FC2), cuda_flow_b(frame1.size(), CV_32FC2);
brox_flow->calc(frame0, frame1, cuda_flow_f);
brox_flow->calc(frame1, frame0, cuda_flow_b);
// split flow to horizontal and vertical component
cv::Mat flow_f, flow_b;
cuda_flow_f.download(flow_f);
cuda_flow_b.download(flow_b);
std::vector<cv::Mat> CC_f, CC_b;
cv::split(flow_f.reshape(1), CC_f);
cv::split(flow_b.reshape(1), CC_b);
cv::Mat fu(CC_f[0]), fv(CC_f[1]), bu(CC_b[0]), bv(CC_b[1]);
```
for computing optical flow.

Just in case someone runs to the same issue. (For OpenCV 4.6)
