### ISSUE TITLE
Does project website stop working?

### ISSUE THREAD

**Issue by lkwargs** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#41]

**Comment by xiangdonglai** [comment]
The server was down for a while due to a power outage. Sorry for the inconvenience.

**Comment by miaoYuanyuan** [comment]
@xiangdonglai the webset seems stop working , where can I get the dataset?

**Comment by xiangdonglai** [comment]
The server is down again. Unfortunately I cannot physically access to our server due to the lockdown of our campus. For the time being you can try to download the dataset at
http://posefs1.perception.cs.cmu.edu/mtc/mtc_dataset.tar.gz
by using wget or copy paste it into your web browser. The file is 270GB large.

**Comment by miaoYuanyuan** [comment]
I see, Thank you!
